apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRRWxONCtPdTRIVmtkcFJpVk9iNklTakFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNVEl3TkRFeU1qUXpNMW9YRFRNMU1USXdNakV5TWpRegpNMW93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCQjU3UEJPTHJ4RGl1S0kxYnZXNW5IREVnd1RKeDl5R3p1TjU2QmJpWFpZditiV1FwZlF6R3B2aXFIcSsKY0RGS1RJSjFxTnBpYUVWZUtGcUVMRlRXbExTallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU5eG5mRWJtYnFQSXI5UzhGYXczVTJxVDZmQmN3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnSEFTNW5hRWoKbER5QjByVDQzMDdoeE5tY3hvcFV5R3FZUVVDUTBrOXdEbk1DSVFDT1NyQ0ZDelhaU29keW8yZ1ZBNnpCREI1bgpNdndDZlFTMFRYRXJZd1Q0dmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://69317d813aaeaabc41fac605.dcptunnel.net:6443
    name: test-load-cluster-69317d81
contexts:
  - context:
      cluster: test-load-cluster-69317d81
      namespace: default
      user: 68b0af9e0e82cf468d167c52
    name: 69317d813aaeaabc41fac605
current-context: 69317d813aaeaabc41fac605
kind: Config
users:
  - name: 68b0af9e0e82cf468d167c52
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVN1Z0F3SUJBZ0lSQU5CYi85ZytEK2V4cWRaS0E1SUtGc2t3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV5TURReE1qSTFNek5hRncweU5qRXlNRFF4TWpJMQpORE5hTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkJqMUxLQnowdXZDTklGSWZQaExrK2lOeUlQN0J4a1EKZ2thV2FNYllmUXVsaFpIbEM4TEV4WHJHdjhQQkw0ZVJQMmRQMFJlcmdDNHhBQ1ZrMkcrRXdmQ2pTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlQzCkdkOFJ1WnVvOGl2MUx3VnJEZFRhcFBwOEZ6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQWNwT1ZYZHFsbDJqS3oKTXlDYVZRRHkwK0JYSVM2SzFUbVdFaDVLdVFFWGZnSWhBSUNmZWw2eEJVWW1mSG1WSmxJMTEzZ1AzMmU4OHBmOApzTnpmMVNRK0EwM00KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUppTkFKUzIxR3pZNHdjZEFTU1pnbC9lQXZBM1pGM0ZtemIzcEtveFZyLzVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFR1BVc29IUFM2OEkwZ1VoOCtFdVQ2STNJZy9zSEdSQ0NScFpveHRoOUM2V0ZrZVVMd3NURgplc2EvdzhFdmg1RS9aMC9SRjZ1QUxqRUFKV1RZYjRUQjhBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
